// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Streaming delta for a dynamic tool call's argument JSON.
 */
export type DynamicToolCallArgumentsDeltaNotification = { threadId: string, turnId: string, itemId: string, callId?: string, delta: string, };
