// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadRevertResponse = {
/**
 * Updated metadata. Hydrate retained turns separately through pagination.
 */
thread: Thread, turnsBackwardsCursor: string | null, itemsBackwardsCursor: string | null, };
