// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Replaces paginated conversation history with the prefix before a turn.
 * This does not undo changes to files.
 */
export type ThreadRevertParams = { threadId: string, beforeTurnId: string, };
